ALTER TABLE prediction_history 
ADD COLUMN dia_da_semana VARCHAR(20),
ADD COLUMN atraso_previsto BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN modelo_versao VARCHAR(50),
ADD COLUMN tempo_resposta_ms DOUBLE PRECISION,
ADD COLUMN status BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN request_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
