ALTER TABLE prediction_history
ADD COLUMN IF NOT EXISTS dia_da_semana VARCHAR(20);
ALTER TABLE prediction_history
ADD COLUMN IF NOT EXISTS atraso_previsto BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE prediction_history
ADD COLUMN IF NOT EXISTS modelo_versao VARCHAR(50);
ALTER TABLE prediction_history
ADD COLUMN IF NOT EXISTS tempo_resposta_ms DOUBLE PRECISION;
ALTER TABLE prediction_history
ADD COLUMN IF NOT EXISTS status BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE prediction_history
ADD COLUMN IF NOT EXISTS request_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;